name: todo_app_clean_acrhitechture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  logger: ^1.1.0
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  injectable_generator: ^1.5.3
  easy_localization: ^3.0.0
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.7
  equatable: ^2.0.3
  google_sign_in: ^5.2.3
  dio: ^4.0.4
  json_serializable: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/